name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you're using

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build
    
    - name: Configure Git
      run: |
        git config --global user.email "erdenesukh@gmail.com"
        git config --global user.name "sukh0128"

    - name: Deploy to GitHub Pages
      run: npm run deploy

    - name: Clean up gh-pages
      run: git worktree prune
